services:
  db:
    image: postgres:alpine
    container_name: prova-postgresql-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prova
      POSTGRES_PASSWORD: prova123
      POSTGRES_DB: provadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: